assets/js/containers.js
Fixed a problem with set_width() method of nested complex Field, where one of the fields, using set_width(), used to jump on the next row.
=> Fix complex set width issue

assets/js/containers.js
Added fix for nested complex fields, which have set_width().
=> Fixed nested complex field set_width()

assets/css/main.css, assets/js/fields.js
Bug fix when you have long labels in tabbed complex.
=> Fix long labels in tabbed complex

assets/css/main.css, assets/js/fields.js
1. Some borders are missing when set_width is used on fields in tabbed complex.
2. Second level complex field covers the plus button's dropdown.
=> Fix style issues in complex layout

assets/css/main.css, assets/js/fields.js, core/Field/Complex_Field.php
Add `tabbed-horizontal` and `tabbed-vertical` tabbed complex field layouts.
=> Tabbed complex

core/Field/Complex_Field.php
=> i18n improvement

assets/css/main.css, core/Container/Container.php, core/Container/Nav_Menu_Container.php, core/Container/User_Meta_Container.php, core/Container/Widget_Container.php, core/Field/Color_Field.php, core/Field/Date_Field.php, core/Field/Field.php, core/Field/Gravity_Form_Field.php, core/Field/Map_Field.php, core/Field/Rich_Text_Field.php, core/Field/Time_Field.php, core/Helper/Helper.php
This change will make these object initialize only when they are needed.
=> Improve field/container initialization

assets/js/fields.js
=> Revert `_models` in complex fields header templates

composer.json
Just updating my site info, since the old URL is no longer valid.
=> Update User Info

config.php
Improve the code, by removing code repetitions.
The next step would be to separate this into it's own function.
The reason for that is to have the ability to re-use this piece of code from plugin extensions, like the Icon field and the Template field:
https://github.com/htmlburger/carbon-field-template
https://bitbucket.org/htmlburger/carbon-field-icon
=> Refactor dinamic url generation

assets/js/fields.js
The media popup triggered from Image field, does not mark current state on the image at all.
This patch will fix that. Hopefully this can be merged into the milestone/2.0
=> Fix for the Media popup current state

assets/js/fields.js
Fix JS error triggered when initially loading the Media popup, for field that has no image setup. It was previously triggering JS error:
```
A "url" property or function must be specified
```
=> Fix JS error related to media popup

core/Field/Field.php
Added support for an array in the set_attribute () method
=> The method set_attribute () was edited

assets/js/containers/components/network/index.js, assets/js/containers/constants.js, core/Container/Network_Container.php, core/Datastore/Network_Datastore.php, core/Exception/Incorrect_Syntax_Exception.php, core/Helper/Helper.php, core/functions.php, templates/Container/network.php
Add container about network options in Wordpress multisite environment.
=> Add Network Container

core/Toolset/Key_Toolset.php
There was one place to worry about...
=> Fixed that is likely to become a magic number in the future

assets/js/fields/components/media-gallery/index.js, core/Field/Media_Gallery_Field.php
=> Added method to disable inline media editor

core/Field/Association/Queries_Options.php
Fix bug where term association and taxonomy set showing terms from all taxonomies
=> Add taxonomy argument for the terms options sql

core/Toolset/Key_Toolset.php, tests/unit-tests/Key_Toolset/KeyToolsetTest.php
@jorostoyanov I introduced a bug, that is a fix for #745
=> Forgot esc_like is not a global function.

packages/metaboxes/containers/term-meta/index.js
=> Fix null access error in term meta container

bin/webpack.vendor.js, packages/core/fields/oembed/index.js
=> Fix trying to use jquery incorrectly in the oEmbed field

packages/core/fields/datetime/style.scss
=> Fix date field not wrapping its elements when in the sidebar 

packages/core/fields/rich-text/index.js
=> Fix rich-text field component unmounting when not visible

packages/core/utils/hex-and-rgba.js
=> Fix color field resetting

packages/core/fields/association/index.js
=> Fix association field selected items labels length

packages/metaboxes/hocs/with-conditional-logic/index.js
Temporary solution for conditional logic issues in complex fields.
=> fix: complex field in metaboxes conditional logic

core/Loader/Loader.php
Fix https://github.com/htmlburger/carbon-fields/issues/857
Fix https://github.com/htmlburger/carbon-fields/issues/727
=> fix: assets context loading

core/Field/Text_Field.php
=> 🐛 FIX: allow 'list' attribute on text fields. Fixes #860

packages/core/fields/multiselect/index.js
=> Preserve multiselect field values selecting order

core/Field/Html_Field.php
=> Improve html field callback to be executed at runtime

packages/core/fields/select/index.js
=> Fix select field value when rendered

packages/core/fields/complex/style.scss
=> Fix complex field buttons appearing over color palette

packages/core/fields/complex/group.js
This MR adds title tags to the complex field type to improve accessibility of the buttons (allows to visually confirm the action of the icon)
=> Accessibility: Add title tags to buttons

core/Field/Hidden_Field.php, packages/core/components/field/index.js
=> Add hiding to hidden field

core/Carbon_Fields.php
=> Change loading to use realpath()

composer.json, core/Pimple/Container.php, core/Pimple/Exception/ExpectedInvokableException.php, core/Pimple/Exception/FrozenServiceException.php, core/Pimple/Exception/InvalidServiceIdentifierException.php, core/Pimple/Exception/UnknownIdentifierException.php, core/Pimple/ServiceIterator.php, phpunit.xml
This MR updates the Pimple container to PHP8-compatible version and fixes PHPUnit tests.
=> PHP8 compitability

packages/core/fields/map/google-map.js, packages/core/fields/rich-text/index.js
Fix blocks preview.
Related Issue #1200
=> Fix blocks preview (#1200)
