htmlburger/carbon-fields

- core/Field/File_Field.php
[`home_url()`](https://codex.wordpress.org/Function_Reference/home_url) + "/wp-includes" only works if you have a default WordPress installation. But since you can basically change all paths, it's better to rely on [`includes_url()`](https://codex.wordpress.org/Function_Reference/includes_url) here.
> Fix path the the default thumb image

- assets/css/main.css
This fixes a CSS issue, that prevents the showing of the complex "Add" button dropdown on "Add term" page.
> Term Meta Styling Update

- core/Field/Predefined_Options_Field.php
The `set_options` method in the `Predefined_Options_Field` class is using `array_merge`. This results in renumbering of the elements of the array, which is not desired in some/most cases.
> Fix for set_options method in the Predefined_Options_Field class

- core/Datastore/Meta_Datastore.php
Nav Menu fields did not save meta in the correct format.
For example:
It saves `_crb_example-64`, while it should save just `_crb_example`. So when trying to get the nav-menu meta with `carbon_get_post_meta($item->ID, 'crb_example');` - it did not work.
> Fix Nav_Menu_Datastore.php missing dependency in Meta_Datastore.php

- core/Container/Post_Meta_Container.php
- tests/unit-tests/Container/PostMetaContainerConditions.php
This is a solution of https://github.com/htmlburger/carbon-fields/issues/24.
When using `show_on_page()`, `show_on_template()` and `show_on_page_children()` on a `Post_Meta` container, the post type was not being changed to `page` automatically.
This was requiring that users specifically call `->show_on_post_type( 'page' )` in order for the container to be actually shown.
This PR addresses this issue for the 3 specified methods above. 
Tests are also included.
> Set post type to page when using page condition methods on containers

- templates/Container/theme_options.php
This adds a filter for the Theme Options save button label where the filter name is based on the container title. For example, the filter name for "Theme Options" would be "carbon_theme_options_button_label".
This could be useful if you plan to use this container for some custom functionality or if you simply don't like the default "Save Changes" label.
> Add filter for Theme Options save button label

- core/Field/Complex_Field.php
Moves 'array_values' function outside of 'end' function.
Original warning before fix: 
Strict standards: Only variables should be passed by reference in PATH\TO\wp-content\plugins\carbon-fields\core\Field\Complex_Field.php on line 100
> Fixes warning in set_header_template.

- core/Container/Post_Meta_Container.php
Right now the `->show_on_page($page_path|$page_id)` method for `Post_Meta_Container` requires to explicitly provide an integer in case you'd like to use a page ID.
It would be nice if you can use directly functions like `get_option()`, which return a string.
> Allow show_on_page to use string representation of numbers

- core/Helper/Helper.php
This will prevent php warnings, that could potentially appear when extending carbons fields with field that saves serialized data.
> Introducing additional validation

- assets/js/containers.js
- core/Container/Post_Meta_Container.php
- tests/unit-tests/Container/PostMetaContainerConditions.php
Since WP 4.7 Templates will be allowed on custom post types as well. This change reflects that, by removing the enforcement for `page` post type when using `show_on_template`.
_(Potentially this could cause compatibility issue with containers defined without `show_on_post_type`, that relies on this line of code. This is minor issue, and should not cause issues.)_
> WordPress 4.7 compatibility update

- core/Libraries/Sidebar_Manager/assets/js/app.js
The "Add Sidebar" button is displayed on User edit screens, and Custom post type screen, and probably few other locations. This will limit it to widgets.php only.
> "Add Sidebar" button issue

- core/Container/User_Meta_Container.php
This is needed, when we are allowing access for custom user roles to the administration interface.
Custom User Roles may be asked to fill in user details, like address, city, state etc. This change will allow the container to be visible for them.
The method `show_for` accepts an array, containing either or both `roles` and `capabilities`, which will be limiting the container visibility with logical `AND`, so when passing both, both will need to be evaluated to `true`.
> Integrate show_for method for User Meta Container

- assets/js/fields.js
This fixes the sidebar name being stored in database, rather than the sidebar ID.
> Fix sidebar field incorrect value stored in DB

- core/Field/Association_Field.php
This occurs when a specific term is selected from the Association, and later the term is deleted from administration.
PHP error text:
```
var carbon_json = string(187) "Notice: Trying to get property of non-object in .../vendor/htmlburger/carbon-fields/core/Field/Association_Field.php on line 113"
```
Field Definition:
```
Field::make( 'association', 'categories', __('Categories', 'crb') )
->set_types( array(
array(
'type' => 'term',
'taxonomy' => 'category',
)
) )
```
> Fix php error with association when term deleted

- assets/js/fields/helpers.js
Some plugins may add new image type support (eg for svg) with non-standard size names. In that case this code will crash and the attachment will not be saved. This change resolves that.
The plugin causing the hiccup is using non-standard WP naming's, so I'll do a pull request for them too, but it seems desirable for the thumbnail preview to fail in these rare cases, rather than the attachment fail completely.
> More defensive check for thumbnail url.

- .travis.yml
5.3 is no longer available on trusty, which is the default.
https://github.com/travis-ci/travis-ci/issues/2963
> Rollback to "precise"-based test images

- core/Helper/Helper.php
`$_SERVER` variables might not always be set (e.g. CLI). Wrapping this condition in `isset()` can eliminate a WP Debug notice.
> $_SERVER['REQUEST_METHOD']

- core/Field/Complex_Field.php
- core/Field/Field.php
I found myself several times in need to a hook that will allow me to make some changes before saving. After I dug a bit in the the code, I think this is the best way of doing it.
It will close #363 #378 and #379 
-----
Usecase: setting an unique ID to a field
```
add_filter('carbon_fields_before_field_save', function ($instance) {
if ($instance->get_name() === '__sidebar_id' && empty($instance->get_value())) {
$instance->set_value(uniqid());
}
return $instance;
}, 10, 3);
```
This PR also adds the next two filters:
- `carbon_fields_before_field_delete`
- `carbon_fields_before_complex_field_save`
> Before save & before delete hooks

- assets/js/containers/components/network/index.js
- assets/js/containers/components/theme-options/index.js
IE11 has a breaking bug that causes an infinite redirect.
IE bug ticket: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/3740423/
> Temporarily disable hash syncing for tabbed containers

- package.json
- yarn.lock
Update flatpickr version which fixes the issue where clicking the next month button would not switch the current month
> Fix date picker month not switching properly

- packages/metaboxes/fields/association/index.js
The findFieldByName function was returning the wrong field if the
Complex field name's was the starting string of the Association name.
Ex:
Complex field name: post_people
Association field name: post_people_assoc
More details here:
https://github.com/htmlburger/carbon-fields/issues/636
> Fixing Association field issue when embeded in Complex field

- packages/core/fields/complex/style.scss
The complex field inserter menu does not have a z-index meaning that the 'Thank you for creating with WordPress' Banner shows over the menu, making the last item unselectable.
> Fix complex field inserter z-index

- packages/core/fields/media-gallery/index.js
First of all, I'm not a React developer, and I may not have followed the usual workflow.   
I didn't not found any built files in your repo, so I think It's okay.
> #734 Avoid Media Gallery crash with images /wo thumbnail

- packages/core/utils/fetch-attachments-data.js
Currently, the media_gallery field can only save **X** attachments.
**X** being the number set in Settings -> Reading -> posts_per_page
There are a few open issues that mention this:
https://github.com/htmlburger/carbon-fields/issues/665
https://github.com/htmlburger/carbon-fields/issues/688
This commit allows the media_gallery field to save any number of attachments.
**Steps to reproduce the problem**:
1. Go to Settings -> Reading
2. Set "Blog pages show at most" to **X** (any number)
3. Add more than **X** images to a media_gallery field and save changes
4. Only the first **X** images would be saved.
> Allow media_gallery field to save any number of attachments

- packages/metaboxes/containers/widget/index.js
There is a `trigger( 'change' );` when the arrow of a widget title is clicked. But if a user clicks on anywhere else of the title section ( which also opens the widget ), the event is not triggered and the 'Save' button stays disabled. This modification fixes the problem.
> Fix disabled 'Save' button when on widget init

- languages/carbon-fields-ui.pot
- packages/core/fields/complex/index.js
> Add missing localization for complex field no entries message

- packages/metaboxes/components/field/style.scss
> Fix term meta fields labels overlapping when not full width

- core/Provider/Container_Condition_Provider.php
the condition user_capability does not work as there is a typo in the factories list;
user_capabiltiy
instead of 
user_capability
This PR fixes this for the most recent version.
If at all possible, please back-port to v2.2.x.
> Fix a typo that has been present since at least 2.2.0

- core/Container/Block_Container.php
- packages/blocks/components/block-edit/index.js
Fix #777 
Deprecates `set_preview_mode` in favor of `set_mode`
> Implement method for changing blocks edit mode

- packages/core/fields/association/style.scss
The issue was that when introduced with a long title in the Association Field - the field was expanding beyond it's parent width.
I've added styles to the `<fieldset>` wrapper of the fields and set a max-width for the Association Fields container.
Also there are added styles for the chosen field on the right.
> Add style fixes for association field

- core/Helper/Helper.php
Related to this issue:
https://github.com/htmlburger/carbon-fields/issues/949
Replacing calls to basename() (default PHP function) to mb_basename() (as defined [here](https://www.php.net/manual/en/function.basename.php#121405)) inside core/Helper/Helper.php
basename() doesn't handle mutibyte characters.
> Handling multibyte filenames for the "image" type carbon field

- core/Container/Block_Container.php
Replace deprecated 'block_categories' with 'block_categories_all' which was [introduced](https://core.trac.wordpress.org/ticket/52920) in WordPress 5.8.
> Switch to 'block_categories_all'

- bin/webpack.blocks.js
- bin/webpack.core.js
- bin/webpack.metaboxes.js
- bin/webpack.vendor.js
- core/Loader/Loader.php
- package.json
- packages/core/fields/map/google-map.js
- packages/core/fields/rich-text/index.js
- yarn.lock
https://github.com/htmlburger/carbon-fields/issues/1198
After the release of WordPress v6.4 Carbon Fields have stopped working.
There were several issues that are addressed in this PR:
* lodash is added as dependency to Carbon Fields scripts
* Webpack is now upgraded to v5 from v4
* Package `observe-resize` is replaced with the ResizeObserver API
> Add support for WordPress v6.4

- core/Container.php
- core/Container/Container.php
- core/Container/Nav_Menu_Item_Container.php
- core/Container/Theme_Options_Container.php
- core/Datastore/Datastore.php
- core/Field.php
- core/Field/Field.php
Same as #1223 but uses static::class where appropriate.
> chore: Replace get_class() by static::class
